# Generated by Django 3.2 on 2023-02-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230131_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
