# Generated by Django 3.2 on 2023-02-02 20:23

from django.db import migrations, models
import django.db.models.deletion
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.category'),
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=0, validators=[reviews.validators.year_title]),
            preserve_default=False,
        ),
    ]
