# Generated by Django 3.2 on 2023-02-02 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_title_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Evaluation'),
        ),
    ]
