# Generated by Django 3.2 on 2023-02-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_genretitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Evaluation'),
        ),
    ]
